### ISSUE TITLE
Soft parts can be removed now

### ISSUE THREAD

**Issue by loveuseless** [dvize/PIRM#1]
hey, i updated PRIM and now it allows to remove soft parts of armor, They become broken if done so, i use unrestricted plates and it conflicts with that too now. There was an issue with  unrestricted plates with insurance, armor comes back without soft parts if you are allowed to change them. pretty sure your mode will have the same error
Is there any way to disable soft part removal? Cuz i like changing plates a lot and PRIM in general

**Comment by dvize** [comment]
I responded to you on the hub. Don't use the other plate mod. My guess is
he got rid of the filters making it so that it spawns without it. Also
there is a toggleable option in the bepinex config menu to prevent being
able to swap all plates
